# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'Whole-Body GAN Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Whole-Body GAN Demo
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
end
